# -*- mode: ruby -*-
# vim: set ft=ruby :


MACHINES = {
  :nginx => {
        :box_name => "centos/7"
        #:ip_addr => '192.168.56.41'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "forwarded_port", guest: 8080, host: 8080
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
          
          box.vm.provision "ansible" do |ansible|
            #ansible.verbose = "vv"
            ansible.playbook = "web.yml"
            ansible.become = "true"
          end

      end
  end
end
